apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-k8s-conf
  labels:
    name: prometheus-k8s-conf
  namespace: observability
data:
  prometheus.rules: |-
    groups:
    - name: demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'demo-server'
        static_configs:
          - targets: ['otel-collector.observability.svc.cluster.local:8889']
        